os:
  - linux
  - osx
language: generic
env:
  global:
  - SWIFT_VERSION=3.0
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(cat ./install-swiftenv.sh)"
script:
  - swift build --clean # clean built artifacts if present
  - swift package fetch # clones all dependencies
  - swift build -Xcc -fblocks -Xlinker -rpath -Xlinker $(pwd)/.build/debug/ # build project
  - swift test #run tests
